### PR TITLE
Added sortDescending, sortBy and sortByDescending methods inspired by…

### PR DESCRIPTION
**Pull request by MrPlow442**
… kotlin methods with the same name.

### CODE REVIEW

**Comment by czyzby** [comment]
Thanks.

I'd be grateful if you also updated `CHANGELOG.md` in root directory and `README.md` file of the library that you contribute to when submitting pull requests.

**Comment by MrPlow442** [comment]
Sure. I'll keep that in mind in the future.

**Comment by czyzby** [comment]
Yeah, my bad - should have added it to the contribution guide.

**Comment by czyzby** [comment]
Your utility methods should already be available in the snapshot release.

**Pull request merged**
